[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "seismicif"
authors = [
     { name = "Francois Kamper", email = "francois.kamper@epfl.ch" },
     { name = "Patrick Paitz", email = "patrick.paitz@wsl.ch" },
]
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    # TODO configure install dependencies
    "fastdtw~=0.3.4",
    "ipykernel~=6.29.2",
    "matplotlib~=3.8.3",
    "notebook~=7.4.2",
    "numpy~=1.26.4",
    "obspy~=1.4.0",
    "pandas~=2.2.0",
    "pre-commit~=4.2.0",
    "pyarrow~=20.0.0",
    "pytest~=8.3.5",
    "ruff~=0.11.9",
    "scikit-learn ~= 1.4.1",
    "scipy~=1.12.0",
    "tqdm~=4.67.1",
]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "seismicif.__version__"}

[tool.ruff]
exclude = ["scripts/"]
extend-include = ["*.ipynb"]
target-version = "py310"
line-length = 88

[tool.ruff.lint]
extend-select = [
    "W605",   # pycodestyle: invalid-escape-sequence
    "S102",   # flake8-bandit: exec-builtin
    "INP",    # flake8-no-pep420
    "PYI",    # flake8-pyi
    "PT",     # flake8-pytest-style
    "PGH",    # pygrep-hooks
    "PL",     # Pylint
    "NPY",    # NumPy-specific rules
    "RUF",    # Ruff-specific rules
]
ignore = [
    "NPY002", # numpy-legacy-random
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/**" = ["INP001"]
"[!t][!e][!s][!t][!s]*/**" = ["PT"]
